### ISSUE TITLE
No build job for npm?

### ISSUE THREAD

**Issue by huxoll** [uwehale/node-express-angular#1]
FROM uwehale/alpine-node-bower-git:latest
Removing intermediate container 7575f2ee7971
Step 7 : RUN npm run build
 ---> Running in 418ebaf1c7c4
npm ERR! Linux 4.4.19-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/app/npm-debug.log

**Comment by uwehale** [comment]
npm script was changed from 'build' to 'client' but the dockerfile was not updated. It's fixed.

But running into another docker issue with npm 3 now.   https://github.com/npm/npm/issues/9863
